# Solutions for code challenges {-}

## Chapter 2 {-}

```{r}
library(ggplot2)
v <- c(1, 2)
s <- rnorm(10)

all_vectors <- data.frame(xend = c(v[1], v[1] * s),
                          yend = c(v[2], v[2] * s),
                          Vector = c("Original", rep("Scaled", length(s))),
                          x = 0,
                          y = 0)

ggplot(data=all_vectors, aes(x=x, y=y, xend=xend, yend=yend, color=Vector)) + 
  geom_segment(arrow= arrow(length = unit(0.03, "npc"))) +
  xlim(-4, 4) +
  ylim(-4, 4) + 
  coord_equal()
```

## Chapter 3 {-}

### Exercise 1 {-}
```{r}
v1 <- c(1, 2, 3, 4, 5)
v2 <- c(2, 3, 4, 5, 6)
v3 <- c(3, 4, 5, 6, 7)
w <- c(-1, 3, 2)
result <- v1 * w[1] + v2 * w[2] + v3* w[3]
```

### Exercise 2 {-}

```{r}
v <- c(7, 4, -5, 8, 3)
o <- rep(1, length(v))
ave <- pracma::dot(v, o) / length(v)
```

### Exercise 3 {-}
```{r}
v <- c(7, 4, -5, 8, 3)
w <- runif(length(v))
wAve <- pracma::dot(v, w / sum(w))
```

## Chapter 5 {-}

### Exercise 1 {-}
```{r}
A <- matrix(runif(n=4*2), nrow=4, ncol=2)
B <- matrix(runif(n=4*2), nrow=4, ncol=2)
C <- matrix(NA, nrow=2, ncol=2)
for(coli in 1:2){
  for(colj in 1:2){
    C[coli, colj] <- pracma::dot(A[, coli], B[, colj])
  }
}
```

### Exercise 2 {-}
```{r}
A <- matrix(runif(n=4*4), nrow=4, ncol=4)
Al <- pracma::tril(A)
S <- Al + t(Al)
```

### Exercise 3 {-}
```{r}
D <- matrix(0, nrow=4, ncol=8)
for(d in 1:min(dim(D))){
  D[d, d] <- d
}
```

## Chapter 6 {-}

### Exercise 1 {-}
```{r}
A <- matrix(runif(n=2*4), nrow=2, ncol=4)
B <- matrix(runif(n=4*3), nrow=4, ncol=3)
C1 <- matrix(0, nrow=2, ncol=3)
for(i in 1:4){
  C1 <- C1 + outer(A[, i], B[i, ])
}
C1 - A %*% B
```

### Exercise 2 {-}
```{r}
D <- diag(1:4)
A <- matrix(runif(n=4*4), nrow=4, ncol=4)
C1 <- D * A
C2 <- D %*% A
print(diag(C1))
print(diag(C2))
```

### Exercise 3 {-}
```{r}
A <- diag(runif(3))
C1 <- (t(A) + A) / 2
C2 <- t(A) %*% A
C1 - sqrt(C2)
```

### Exercise 4 {-}
Note that `norm()` requires a matrix as an input, therefore, we convert an atomic vector to a matrix for the norm computation.
```{r}
m <- 5
A <- matrix(runif(n=m*m), nrow=m, ncol=m)
v <- runif(n=m)
LHS <- norm(A %*% v, type = "F")
RHS <- norm(A, type = "F") * norm(matrix(v), type="F")
RHS - LHS # should always be positive
```

## Chapter 7 {-}

### Exercise 1 {-}
```{r}
A <- matrix(runif(n=9*2), nrow=9, ncol=2)
B <- matrix(runif(n=2*16), nrow=2, ncol=16)
C <- A %*% B
```

### Exercise 2 {-}
```{r}
Z <- matrix(0, nrow=5, ncol=5)
N <- matrix(runif(5 * 5), nrow=5, ncol=5)
ZN <-  Z + N * .Machine$double.eps * 1e-307
print(pracma::Rank(Z))
print(pracma::Rank(ZN))
print(norm(ZN, type = "F"))
```

## Chapter 8 {-}
### Exercise 1 {-}
```{r}
A <- matrix(runif(n=4*3), nrow=4, ncol=3) %*% matrix(runif(n=3*4), nrow=3, ncol=4)
B <- matrix(runif(n=4*3), nrow=4, ncol=3) %*% matrix(runif(n=3*4), nrow=3, ncol=4)
n <- pracma::nullspace(A)
print(B %*% A %*% n) # zeros vector
print(A %*% B %*% n) # not zeros vector
```
### Exercise 2 {-}
```{r}
A <- matrix(runif(n=16*9), nrow=16, ncol=9) %*% matrix(runif(n=9*11), nrow=9, ncol=11)
rn <- pracma::nullspace(A)
ln <- pracma::nullspace(t(A))
r <- pracma::Rank(A)
print(ncol(rn) + r)
print(ncol(ln) + r)
```

