--- 
title: 'R-version of the code for "Linear Algebra: Theory, Intuition, Code" by _Mike X Cohen_'
author: "Alexander (Sasha) Pastukhov"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
description: "R-version of the code for _Linear Algebra: Theory, Intuition, Code_ by Mike X Cohen"
---

# Introduction {-}

This is an R-version of the code for ["Linear Algebra: Theory, Intuition, Code"](https://www.amazon.com/Linear-Algebra-Theory-Intuition-Code/dp/9083136604) by [Mike X Cohen](http://www.mikexcohen.com/). I have tried to keep the code as close to the original as possible even if it went against the spirit of R. E.g., some loops can be replaced with vectorized operations, tidyverse piping approach, or `apply()`/`replicate()`/`purrr::map()`. In most cases, I use `library::` disambiguation to make it easier to understand which function belongs to which package, in addition to importing libraries via `library()`.

## Libraries the code relies upon {-}

Matrix calculations

* [pracma](https://rdrr.io/cran/pracma/)
* [geigen](https://rdrr.io/cran/geigen/) for generalized eigenvalues
* [matrixcalc](https://rdrr.io/cran/matrixcalc/) for raising matrix to the power

[Tidyverse](https://tidyverse.org/) packages for data wrangling, you can install all relevant packages (including ggplot2) via `install.packages("tidyverse")`.

* [dplyr](https://dplyr.tidyverse.org/)
* [tidyr](https://tidyr.tidyverse.org/)
* [reshape2](https://www.rdocumentation.org/packages/reshape2/versions/1.4.4)

Graphics

* [ggplot2](https://ggplot2.tidyverse.org/) for plotting
* [plotly](https://plotly.com/r/) for 3D surface plot
* [patchwork](https://patchwork.data-imaginist.com/) to create a composite figure out of multiple plots
* [RColorBrewer](https://rdrr.io/cran/RColorBrewer/) for color schemes
* [imager](https://dahtah.github.io/imager/) for working with images

